# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - "*"

resources:
  repositories:
  - repository: sonic-swss
    type: github
    ref: refs/heads/202012
    name: Azure/sonic-swss
    endpoint: build

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-buster
      swss_common_artifact_name: sonic-swss-common
      artifact_name: sonic-sairedis
      syslog_artifact_name: sonic-sairedis.syslog
      run_unit_test: true

- stage: BuildArm
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      timeout: 180
      pool: sonicbld
      sonic_slave: sonic-slave-buster-armhf
      swss_common_artifact_name: sonic-swss-common.armhf
      artifact_name: sonic-sairedis.armhf
      syslog_artifact_name: sonic-sairedis.syslog.armhf

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      timeout: 180
      pool: sonicbld
      sonic_slave: sonic-slave-buster-arm64
      swss_common_artifact_name: sonic-swss-common.arm64
      artifact_name: sonic-sairedis.arm64
      syslog_artifact_name: sonic-sairedis.syslog.arm64

- stage: BuildSwss
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-swss-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-buster
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      artifact_name: sonic-swss

- stage: BuildDocker
  dependsOn: BuildSwss
  condition: succeeded('BuildSwss')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      swss_artifact_name: sonic-swss
      artifact_name: docker-sonic-vs

- stage: Test
  dependsOn: BuildDocker
  condition: succeeded('BuildDocker')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      log_artifact_name: log
